apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebtestApp
  labels:
    app: mywebtestApp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mywebtestApp
  template:
    metadata:
      labels:
        app: mywebtestApp
    spec:
      containers:
      - name: mywebtestApp
        image: sadanandrshastri/customtomcat:latest
        ports:
        - containerPort: 8080
---
        apiVersion: v1
        kind: Service
        metadata:
          name: hello
          labels:
            app: hello
        spec:
          ports:
          - port: 80
            targetPort: 8080
          type: LoadBalancer
          selector:
            app: mywebtestApp