apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebtestapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mywebtestapp
  template:
    metadata:
      labels:
        app: mywebtestapp
    spec:
      containers:
      - name: mywebtestapp
        image: sadanandrshastri/customtomcat:tagversion
        ports:
        - containerPort: 8080    
---
apiVersion: v1
kind: Service
metadata:
  name: mywebtestapplb
spec:
    type: LoadBalancer
    selector:
      app: mywebtestapp
    ports:
      - protocol: TCP
        port: 8888
        targetPort: 8080      
