apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebtestApp-deployment
  labels:
    app: mywebtestApp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mywebtestApp
  template:
    metadata:
      labels:
        app: mywebtestApp
    spec:
      containers:
      - name: mywebtestApp
        image: sadanandrshastri/customtomcat:latest
        ports:
        - containerPort: 80
