apiVersion: apps/v1
kind: Deployment
metadata:
 name: mywebtestApp
 labels:
  app: mywebtestApp
spec:
 replicas: 2
 selector:
  matchLabels:
   app: mywebtestApp
 template:
  metadata: 
   labels:
    app: mywebtestApp
  spec:
   containers:
   - name: mywebtestAppk8
     image: sadanandrshastri/customtomcat:latest
     ports:
     - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: mywebtestAppLB
spec:
  type: LoadBalancer
  selector:
    app: mywebtestAppLB
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080